version: '2'

services:
  db:
    image: mariadb
    container_name: str-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: str
      MYSQL_ROOT_PASSWORD: secret

  web:
    container_name: str-backend
    build: .
    tty: true
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
