default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: 127.0.0.1 # Put your local network address here
  database: str
  username: root
  password: secret
  socket: /var/run/mysqld/mysqlx.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
