default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: octopus_app_db
  username: root
  password: password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
